# Knowledge Base CMS

NOTE: This README file was generated by AI.  Some of it is accurate... some, not so accurate. :)  

This project code was created 99% by AI using Cursor and Claude.  It is a modern, multilingual Knowledge Base Content Management System built with Python Flask, featuring a rich text editor and comprehensive admin interface.

## Features

- 🌐 Multilingual support with content in multiple languages (English, Japanese, Chinese, Korean, Russian)
- 📝 Rich text editor (Quill.js) with image upload capabilities
- 🔍 Full-text search functionality
- 🔒 Secure admin interface
- 📱 Responsive design for all devices
- 🎯 Topic-based content organization
- 🔄 Drag-and-drop article reordering
- 🖼️ Image management system
- 🔍 SEO-friendly URLs
- 📊 Basic analytics tracking

## Technical Stack

- **Backend**: Python Flask
- **Database**: SQLite with SQLAlchemy ORM
- **Frontend**: Bootstrap 5, jQuery
- **Rich Text Editor**: Quill.js
- **Testing**: Pytest with Playwright for E2E testing
- **Image Processing**: Pillow
- **Search**: SQLite FTS5

## Prerequisites

- Python 3.8 or higher
- pip (Python package installer)
- Node.js and npm (for frontend dependencies)
- Virtual environment (recommended)

## Installation

1. Clone the repository:
```bash
git clone https://github.com/joegiglio/cursor2-kb
cd cursor2-kb
```

2. Create and activate a virtual environment:
```bash
python -m venv venv
source venv/bin/activate  # On Windows: venv\Scripts\activate
```

3. Install Python dependencies:
```bash
pip install -r requirements.txt
```

4. Install frontend dependencies:
```bash
npm install
```

5. Set up environment variables:
```bash
cp .env.example .env
```
Edit `.env` with your configuration settings.

6. Initialize the database:
```bash
flask db upgrade
flask init-db
```

7. Create an admin user:
```bash
flask create-admin
```

## Running the Application

1. Start the development server:
```bash
flask run
```

2. Access the application:
- Main site: `http://localhost:5000`
- Admin interface: `http://localhost:5000/admin`

## Testing

1. Install test dependencies:
```bash
pip install -r requirements.txt
```

2. Install Playwright browsers:
```bash
playwright install
```

3. Run tests:
```bash
pytest
```

For end-to-end tests:
```bash
pytest tests/e2e
```

## Configuration

Key configuration options in `.env`:

```ini
SECRET_KEY=your-secret-key
UPLOAD_FOLDER=uploads
MAX_CONTENT_LENGTH=16777216
ALLOWED_EXTENSIONS=png,jpg,jpeg,gif
DATABASE_URL=sqlite:///knowledge_base.db
```

## Directory Structure

```
knowledge-base-cms/
├── app/
│   ├── models/
│   │   ├── __init__.py
│   │   ├── topic.py
│   │   └── article.py
│   ├── routes/
│   │   ├── __init__.py
│   │   ├── admin.py
│   │   └── public.py
│   ├── static/
│   │   ├── css/
│   │   ├── js/
│   │   └── images/
